@extends('mail_content.layout')

@section('content')
<table align="center" width="100%" cellpadding="0" cellspacing="0" style="background:#002244;">
    <tr>
        <td valign="top" align="left" style="padding: 0px;">
            <table align="center" cellpadding="0" cellspacing="0" style="background: #fff; max-width: 800px;">
                <tr>
                    <td>
                        <table align="center" cellpadding="0" cellspacing="0" style="border-bottom: 2px solid #ddd; height: 120px; max-width: 700px;">
                            <tr>
                                <td>
                                    <a href="https://trustpatrick.com">
                                        <img src="https://marksallpros.s3-us-west-2.amazonaws.com/logo_TrustPatrick.com_Retina.png" alt="logo" />
                                    </a>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td>
                        <table align="center" cellpadding="0" cellspacing="0" style="max-width: 700px;">
                            <tr>
                                <td style="font-family: arial,helvetica,sans-serif; color: #808080; font-size: 14px;">
                                    <p>
                                        <strong>Dear <?php echo '{{ FIRST_NAME }}'; ?></strong>,
                                    </p>
                                    <br /><br />
                                    <p>We received your request to be contacted by <?php echo '{{ COMPANY_NAME }}'; ?> for <?php echo '{{ SERVICE_CATEGORY }}'; ?>.</p>
                                    <p>To fight spam, we'd like you to confirm your request so we know you're human!</p>
                                    <p>Please confirm your request by clicking on the button below.</p>
                                    
                                    <br /><br />
                                    <p style="text-align:center;">
                                        <a href="<?php echo '{{ CONFIRM_REQUEST }}'; ?>" style="border: none rgb(26, 178, 148); color: rgb(255, 255, 255); display: inline-block; font-weight: 900; outline: none; text-decoration: none; color: #efefef; background-color: rgb(27, 64, 115); padding: 12px 18px;" target="_blank">Confirm My Request </a>
                                    </p>
                                    <br /><br />
                                    <p style="font-family: arial,helvetica,sans-serif; color: #808080; font-size: 14px;">
                                        Thank you, <br /><br />
                                        The TrustPatrick.com Team <br />(866) 826-7840
                                    </p>
                                    <br /><br />
                                    <p style="text-align:center; font-family: arial,helvetica,sans-serif; color:#808080; font-size:14px;">If you received this confirmation email in error, simply ignore this email and do not click the button.</p>
                                    
                                    <br /><br />
                                    <p style="text-align:center; font-family: arial,helvetica,sans-serif; color:#808080; font-size:10px; line-height: 14px;">
                                        TrustPatrick.com National Address 3531 S Logan St, Suite D212 Englewood, CO 80113
                                        <br /><br />
                                        Request generated by: <?php echo '{{ REQUEST_GENERATE_LINK }}'; ?><br />
                                        Date: <?php echo '{{ DATE }}'; ?><br />
                                        URL: <?php echo '{{ URL }}'; ?>
                                    </p>
                                    <br /><br />
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td align="center" style="background: #363839;">
                        <table align="center" width="100%" cellpadding="0" cellspacing="0">
                            <tr>
                                <td>&nbsp;</td>
                            </tr>
                            <tr>
                                <td>
                                    <p style="color: #ffffff; font-family: 'Open Sans', sans-serif; font-size: 35px; font-weight: 700; letter-spacing: 0; text-align: center;">Connect With Us</p>
                                </td>
                            </tr>
                            <tr>
                                <td>&nbsp;</td>
                            </tr>
                            <tr>
                                <td>
                                    <table align="center" cellpadding="0" cellspacing="0" style="max-width: 160px;">
                                        <tr>
                                            <td width="40" align="left" valign="top">
                                                <a href="<?php echo '{{ FACEBOOK_LINK }}'; ?>" style="border: none; display: block; font-size: 1px; height: 35px; line-height: 35px; outline: none; text-decoration: none; width: 35px;">
                                                    <img src="https://marksallpros.s3-us-west-2.amazonaws.com/user-email/facebook.png" alt="yt" style="-ms-interpolation-mode: bicubic; border: 0; display: block; font-size: 1px; height: 35px; line-height: 35px; outline: 0; text-decoration: none; width: 35px;" width="35" border="0" />
                                                </a>
                                            </td>
                                            <td width="40" align="left" valign="top">
                                                <a href="<?php echo '{{ TWITTER_LINK }}'; ?>" style="border: none; display: block; font-size: 1px; height: 35px; line-height: 35px; outline: none; text-decoration: none; width: 35px;">
                                                    <img src="https://marksallpros.s3-us-west-2.amazonaws.com/user-email/twitter.png" alt="ig" style="-ms-interpolation-mode: bicubic; border: 0; display: block; font-size: 1px; height: 35px; line-height: 35px; outline: 0; text-decoration: none; width: 35px;" width="35" border="0">
                                                </a>
                                            </td>
                                            <td width="40" align="left" valign="top">
                                                <a href="<?php echo '{{ INSTAGRAM_LINK }}'; ?>" style="border: none; display: block; font-size: 1px; height: 35px; line-height: 35px; outline: none; text-decoration: none; width: 35px;">
                                                    <img src="https://marksallpros.s3-us-west-2.amazonaws.com/user-email/ig.png" alt="behance" style="-ms-interpolation-mode: bicubic; border: 0; display: block; font-size: 1px; height: 35px; line-height: 35px; outline: 0; text-decoration: none; width: 35px;" width="35" border="0">
                                                </a>
                                            </td>
                                            <td width="40" align="left" valign="top">
                                                <a href="<?php echo '{{ YOTUBE_LINK }}'; ?>" style="border: none; display: block; font-size: 1px; height: 35px; line-height: 35px; outline: none; text-decoration: none; width: 35px;">
                                                    <img src="https://marksallpros.s3-us-west-2.amazonaws.com/user-email/you_tube.png" alt="twitter" style="-ms-interpolation-mode: bicubic; border: 0; display: block; font-size: 1px; height: 35px; line-height: 35px; outline: 0; text-decoration: none; width: 35px;" width="35" border="0">
                                                </a>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td>&nbsp;</td>
                            </tr>
                            <tr>
                                <td align="center" style="color: #DDDDDD; font-family: 'Open Sans', sans-serif; font-size: 13px; font-weight: normal; letter-spacing: 0.02em; line-height: 23px; text-align: center; ">
                                    <a href="<?php echo '{{ UNSUBSCRIPTION_LINK }}'; ?>" style="border: none; color: #DDDDDD; display: inline-block; font-family: 'Open Sans', sans-serif; outline: none; text-align: center; text-decoration: underline;"><font face="'Open Sans', sans-serif" style="padding:0 15px;">Unsubscribe</font>|</a>
                                    <a href="https://trustpatrick.com/contact/" style="border: none; color: #DDDDDD; display: inline-block; font-family: 'Open Sans', sans-serif; outline: none; text-align: center; text-decoration: underline;"><font face="'Open Sans', sans-serif" style="padding:0 15px;">Contact Us</font>|</a>
                                    
                                    <a href="https://trustpatrick.com/privacy-policy/" style="border: none; color: #DDDDDD; display: inline-block; font-family: 'Open Sans', sans-serif; outline: none; text-align: center; text-decoration: underline;"><font face="'Open Sans', sans-serif" style="padding:0 15px;">Privacy Policy</font>|</a>

                                    <a href="https://trustpatrick.com/terms-of-use/" style="border: none; color: #DDDDDD; display: inline-block; font-family: 'Open Sans', sans-serif; outline: none; text-align: center; text-decoration: underline;"><font face="'Open Sans', sans-serif" style="padding:0 15px;">Terms Of Use</font>|</a>

                                    <a href="https://trustpatrick.com/infringement-policy/" style="border: none; color: #DDDDDD; display: inline-block; font-family: 'Open Sans', sans-serif; outline: none; text-align: center; text-decoration: underline;"><font face="'Open Sans', sans-serif" style="padding:0 15px;">Infringment Policy</font></a>
                                </td>
                            </tr>
                            <tr>
                                <td>&nbsp;</td>
                            </tr>
                            <tr>
                                <td align="center" style="font-family: arial,helvetica,sans-serif; color:#DDDDDD; font-size:10px; line-height: 14px;">
                                    <p>
                                        Request generated by: <?php echo '{{ REQUEST_GENERATE_LINK }}'; ?><br />
                                        Date: <?php echo '{{ DATE }}'; ?><br />
                                        URL: <?php echo '{{ URL }}'; ?>
                                    </p>
                                </td>
                            </tr>
                            <tr>
                                <td>&nbsp;</td>
                            </tr>
                            <tr>
                                <td>&nbsp;</td>
                            </tr>
                            <tr>
                                <td align="center" style="font-family: 'Open Sans', sans-serif; color:#DDDDDD; font-size:10px; line-height: 14px;">
                                    <p>This followup email was sent to <?php echo '{{ EMAIL_FOOTER }}'; ?> because you recently requested to<br>find a pro for <?php echo '{{ MAIN_SERVICE_CATEGORY }}'; ?> from TrustPatrick.com.</p>
                                    <br />
                                    <p>You may unsubscribe from receiving any further communication from us at any time by clicking on the "Unsubscribe" link above.</p>
                                    <br />
                                    <p>&copy; Copyright 2019 TrustPatrick.com 3531 S Logan St, Suite D212 Englewood, CO 80113 All Rights Reserved</p>
                                    <br />
                                    <br />
                                    <br />
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
@endsection