@extends('mail_content.new-layout')

@section('content')
<p style="text-align: center; border-bottom: 1px solid #ddd;">
    <a href="{{ url('/') }}">
        <img src="https://marksallpros.s3-us-west-2.amazonaws.com/logo_TrustPatrick.com_Retina.png" alt="logo"  style="max-width: 320px; padding: 30px;" />
    </a>
</p>
<p>Dear <?php echo '{{ FIRST_NAME }}'; ?>,</p>
<p>We received your request to find a pro for <?php echo '{{ SERVICE_CATEGORY }}'; ?>.</p>
<p>To fight spam, we'd like you to confirm your request so we know you're human!</p>
<p>Please confirm your request by clicking on the button below.</p>
<br />
<p style="text-align: center;"><a class="custom_btn" href="<?php echo '{{ CONFIRM_REQUEST }}'; ?>" target="_blank">Confirm My Request </a></p>
<br />
<p>Thank you,</p>
<p>
	The TrustPatrick.com Team <br />
	(866) 826-7840
</p>
<p style="text-align: center;">If you received this confirmation email in error, simply ignore this email and do not click the button.</p>
<p class="small" style="text-align: center; border-top: 1px solid #ddd; padding-top: 30px;">
    TrustPatrick.com National Address 3531 S Logan St, Suite D212 Englewood, CO 80113
    <br /><br />
    Request generated by: <?php echo '{{ REQUEST_GENERATE_LINK }}'; ?> <br />
    Date: <?php echo '{{ DATE }}'; ?> <br />
    URL: <?php echo '{{ URL }}'; ?>
</p>
@endsection