<?php
$web_settings = \App\Models\Custom::getSettings();
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>{{ env('SITE_TITLE', 'TrustPatrick.com') }}</title>
    <style type="text/css">
        p{
            font-size: 14px;
            line-height: 22px;
        }

        p.small { font-size: 11px; line-height: 15px; }
        .custom_btn{
            color: #fff !important;
            text-decoration: none;
            background: #1b4073;
            font-size: 14px;
            font-weight: 600;
            padding: 10px 15px;
            text-align: center;
        }
        table { border: none; }
        table tr td { color:#808080; font-family: 'Open Sans', sans-serif; }
        a { color: #808080; text-decoration: none; }
    </style>
</head>
<body>



   <table align="center" width="100%" cellpadding="0" cellspacing="0">
    <tr>
        <td valign="top" align="left" style="padding: 0px;">
            <table align="center" cellpadding="0" cellspacing="0" style="background: #fff; max-width: 600px; text-align: center;">
                <tr>
                    <td style="border-bottom: 1px solid #ddd;>
                    <a href={{ url('/') }}">
                        <img src="https://marksallpros.s3-us-west-2.amazonaws.com/logo_TrustPatrick.com_Retina.png" alt="logo"  style="max-width: 320px; padding: 30px;" />
                    </a>
                </td>
            </tr>

            <tr>
                <td style="font-family: arial,helvetica,sans-serif; color: #808080; font-size: 14px; text-align: left;">
                    @yield('content')
                </td>
            </tr>


            <tr>
                <td>&nbsp;</td>
            </tr>
            

          

            <tr>

                <td align="center" style="font-family: arial,helvetica,sans-serif; color:#808080; font-size:10px; line-height: 14px; border-top: 1px solid #ddd">
                    <br/>
                    <br/>
                    TrustPatrick.com 3531 S Logan St, Suite D212 Englewood, CO 80113
                    <br/>
                    <p class="small">
                        Request generated by: <?php echo '{{ REQUEST_GENERATE_LINK }}'; ?><br />
                        Date: <?php echo '{{ DATE }}'; ?><br />
                        URL: <?php echo '{{ URL }}'; ?>
                    </p>
                </td>
            </tr>

        </table>
    </td>
</tr>
</table>




</body>
</html>